services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data2:/var/lib/postgresql/data
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
     - db
    env_file:
      - .env
    volumes:
      - ../users_manager:/app
    ports:
      - "8002:8002"
volumes:
  postgres_data2:
